+ финальное ТЗ спринт 14
zoomja/java-shareit pull request #1
Opened 2024-09-10 19:40 UTC by zoomja

2024-09-11 10:49 UTC, db-exp requested changes

2024-09-11 10:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
+Size можно добавить к NotBlank

2024-09-11 10:49 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final Map<Integer, Item> items = new HashMap<>();
можно еще лучше - спрятать это на уровне Storage, чтобы отделить детали хранения от бизнес-логики

2024-09-12 16:20 UTC, zoomja commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final Map<Integer, Item> items = new HashMap<>();
пока нет БД, решил хранить так, как появится - переделаю

2024-09-12 16:36 UTC, zoomja commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private String name;
добавил

2024-09-12 16:53 UTC, db-exp approved these changes

2024-10-03 16:59 UTC, merged