Add item requests and gateway
zoomja/java-shareit pull request #3
Opened 2024-10-11 22:19 UTC by zoomja

2024-10-12 17:34 UTC, db-exp requested changes

2024-10-12 17:34 UTC, db-exp commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
validation не требуется в части сервера

2024-10-12 17:34 UTC, db-exp commented on server/src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +public class ItemRequestServiceImpl implements ItemRequestService {
Можно применять Transactional/Transactional(readOnly=true) в случае записи/чтения

2024-10-15 10:26 UTC, zoomja commented on server/pom.xml
> +			<artifactId>spring-boot-starter-validation</artifactId>
исправил

2024-10-15 15:57 UTC, db-exp approved these changes

2024-10-29 17:53 UTC, merged